### ISSUE TITLE
Code Structure

### ISSUE THREAD

**Issue by flippmoke** [garrettrayj/php7-mapnik#1]
Hey @garrettrayj I saw your post on the mapnik dev mailing list, I don't have to give a big review but thought I would open a few tickets on your repo here on issues that I might see. 

The first issue I see is that you have all your source in the main directory, its not required but its a lot easier if you put it all in a directory. Is this something required by `phpize`?

Confused by this as it shouldn't be any issue:
`Do NOT compile Boost with C++11. On Mac at least, you'll have a bad time with missing symbols.`

**Comment by garrettrayj** [comment]
I'm not a fan of the directory structure either, but it's PHP extension convention and fighting it is more trouble than it's worth.

That note may be out of style. It's a issue I ran into early that very well could of been caused by a mistake elsewhere. I'll tinker with compiling Boost and update the README in the next release if it turns out to be a phantom.

Thanks again for the feedback!

**Comment by garrettrayj** [comment]
@flippmoke I was a bit late to figuring out the fight was all in my head, but I got there eventually. The sigh I let out after revisiting this project's code could be heard around the world. 😆 Now all the extension classes are organized in the /src folder.

Also, the Boost issue was either a local problem, or something fixed by time. Using stock Mapnik and Boost Homebrew formulas works fine for compiling on Mac now.
